# Generated by Django 3.1 on 2020-08-08 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafeteria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dcid', models.IntegerField(unique=True)),
                ('grade_level', models.SmallIntegerField(default=None, null=True)),
                ('last_sync', models.DateTimeField()),
                ('lunch_id', models.IntegerField(default=None, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=5)),
                ('role', models.SmallIntegerField(choices=[(1, 'Staff'), (2, 'Student')], default=2)),
                ('room', models.TextField(blank=True, default='', max_length=64)),
                ('status', models.BooleanField(default=False)),
                ('user_number', models.IntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafeteria.school')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
