# Generated by Django 3.1 on 2020-08-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_homeroom_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dcid',
            new_name='student_dcid',
        ),
    ]
