# Generated by Django 3.1 on 2020-08-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200819_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_dcid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_dcid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
