# Generated by Django 3.1 on 2020-08-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200819_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
