# Generated by Django 3.1.2 on 2020-11-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200826_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
    ]
