# Generated by Django 3.1.7 on 2021-03-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210329_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='guardian',
        ),
        migrations.AddField(
            model_name='profile',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='guardians', related_query_name='guardian', to='profiles.Profile'),
        ),
    ]
