# Generated by Django 3.1.7 on 2021-03-31 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210329_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='homeroom_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', related_query_name='student', to='profiles.profile', verbose_name='Homeroom Teacher'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lunch_id',
            field=models.IntegerField(default=None, null=True, verbose_name='Lunch ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_dcid',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Student DCID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_dcid',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='User DCID'),
        ),
    ]
