# Generated by Django 3.2.5 on 2021-07-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210331_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='active',
        ),
    ]
