# Generated by Django 3.2.5 on 2021-07-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0010_alter_gradelevel_id'),
        ('profiles', '0011_profile_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafeteria.gradelevel'),
        ),
    ]
