# Generated by Django 3.2.5 on 2021-07-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grade_level',
        ),
    ]
