# Generated by Django 3.2.5 on 2021-08-05 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_profile_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lunch_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
