# Generated by Django 3.2.5 on 2021-08-05 21:00

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    for row in Profile.objects.all():
        row.lunch_uuid = uuid.uuid4()
        row.save(update_fields=['lunch_uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_lunch_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
