# Generated by Django 3.2.5 on 2021-08-05 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_populate_lunch_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lunch_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
