# Generated by Django 3.2.6 on 2021-08-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210807_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cards_printed',
            field=models.SmallIntegerField(default=0, verbose_name='Lunch Cards Printed'),
        ),
    ]
