# Generated by Django 3.1 on 2020-08-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item', to='menu.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('beginning_balance', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('completed', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('DB', 'Debit'), ('CR', 'Credit')], default='DB', max_length=2)),
                ('menu_items', models.ManyToManyField(blank=True, through='transactions.MenuLineItem', to='menu.MenuItem')),
                ('transactee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='menulineitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item', to='transactions.transaction'),
        ),
    ]
