# Generated by Django 3.1.1 on 2020-09-04 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200812_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-submitted']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='new_balance',
            new_name='ending_balance',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
