# Generated by Django 3.1 on 2020-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('active', models.BooleanField(default=False, help_text='Should this school be included when syncing students?')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('school_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=12)),
            ],
        ),
    ]
