# Generated by Django 3.1 on 2020-08-11 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_time', models.TimeField(blank=True, help_text='Time that orders can no longer be accepted. Empty allows orders all day.', null=True)),
                ('homeroom_orders_grade', models.SmallIntegerField(blank=True, help_text='Grade level at which to stop homeroom orders. Empty allows all grades to order through homeroom.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
            ],
        ),
    ]
