# Generated by Django 3.1 on 2020-08-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
