# Generated by Django 3.1.7 on 2021-02-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_delete_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
    ]
