# Generated by Django 3.1.7 on 2021-02-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_auto_20210224_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
    ]
