# Generated by Django 3.1.7 on 2021-02-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0005_auto_20210224_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
    ]
