# Generated by Django 3.2.5 on 2021-07-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0008_alter_gradelevel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='value',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
