# Generated by Django 3.2.5 on 2021-07-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0009_alter_gradelevel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
