# Generated by Django 3.2.5 on 2021-07-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0010_alter_gradelevel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchperiod',
            options={'ordering': ['start_time'], 'verbose_name_plural': 'Lunch Periods'},
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='lunch_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='cafeteria.lunchperiod'),
        ),
        migrations.AddField(
            model_name='lunchperiod',
            name='display_name',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='lunchperiod',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lunchperiod',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='school',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cafeteria.school'),
        ),
        migrations.AlterField(
            model_name='lunchperiod',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
