# Generated by Django 3.2.5 on 2021-07-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0011_auto_20210728_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchperiod',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='lunchperiod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
