# Generated by Django 3.2.5 on 2021-08-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0012_auto_20210728_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchperiod',
            name='teacher_distributes',
            field=models.BooleanField(default=False, help_text='Does the teacher distribute orders for their class?'),
        ),
    ]
