# Generated by Django 3.2.6 on 2021-08-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0014_alter_gradelevel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchperiod',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Lunch Periods'},
        ),
        migrations.AddField(
            model_name='lunchperiod',
            name='sort_order',
            field=models.SmallIntegerField(default=0, help_text='Order in which the lunch period will be displayed'),
        ),
    ]
