# Generated by Django 3.2.6 on 2021-08-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0015_auto_20210825_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchperiod',
            options={'ordering': ['sort_order', 'start_time'], 'verbose_name_plural': 'Lunch Periods'},
        ),
    ]
