# Generated by Django 3.2.6 on 2021-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0016_alter_lunchperiod_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchperiod',
            name='floating_staff',
            field=models.BooleanField(default=False, help_text='Floating period for staff without a homeroom.', verbose_name='floating staff period'),
        ),
    ]
