# Generated by Django 5.1 on 2024-08-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0018_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='closed_message',
            field=models.CharField(blank=True, help_text='The message to be displayed with the cafeteria is closed for a break or holiday.'),
        ),
    ]
