# Generated by Django 3.1 on 2020-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('ENT', 'Entree'), ('SIDE', 'Side'), ('DRINK', 'Drink')], default='', max_length=6)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(help_text='Will be displayed to students', max_length=100)),
                ('sequence', models.SmallIntegerField(help_text='Order item will appear in menu')),
                ('days_available', models.ManyToManyField(blank=True, related_name='menu_items', to='cafeteria.Weekday')),
                ('schools_available', models.ManyToManyField(blank=True, help_text='Choose school availability', related_name='menu_items', to='cafeteria.School')),
            ],
            options={
                'verbose_name_plural': 'Menu Items',
                'ordering': ['sequence'],
            },
        ),
    ]
