# Generated by Django 3.1 on 2020-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='short_name',
            field=models.CharField(blank=True, help_text='Will be used on reports to quickly identify the item', max_length=10),
        ),
    ]
