# Generated by Django 3.2.5 on 2021-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0012_auto_20210728_1629'),
        ('menu', '0002_menuitem_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='lunch_period',
            field=models.ManyToManyField(blank=True, help_text='Choose lunch period availability', related_name='menu_items', to='cafeteria.LunchPeriod', verbose_name='lunch periods available'),
        ),
    ]
