# Generated by Django 3.2.5 on 2021-07-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_lunch_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='schools_available',
        ),
    ]
