# Generated by Django 3.2.6 on 2021-08-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210809_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='short_name',
            field=models.CharField(blank=True, help_text='Will be used on reports to quickly identify the item', max_length=20),
        ),
    ]
