# Generated by Django 3.2.6 on 2021-08-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitem_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='pizza',
            field=models.BooleanField(default=False, verbose_name='Pizza?'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slices_per',
            field=models.SmallIntegerField(default=0, verbose_name='Slices per pizza'),
        ),
    ]
