# Generated by Django 4.2.3 on 2023-08-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20210826_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='Limited availability?'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='max_num',
            field=models.SmallIntegerField(default=0, verbose_name='Maximum number available'),
        ),
    ]
