# Generated by Django 5.2.1 on 2025-09-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menuitem_limited_menuitem_max_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='short_name',
            field=models.CharField(blank=True, help_text='Will be used on reports to quickly identify the item', max_length=24),
        ),
    ]
